baseurl: "http://invkrh.me"
languageCode: "en-us"
title: "Data Hacking"
permalinks:
  post: /:year/:month/:slug/
paginate: 5
googleAnalytics: "UA-74632317-1"

menu:
  main:
    # - Name: "Home"
    #   URL: "/"
    #   weight: 1
    - Name: "Archive"
      URL: "/archive/"
      weight: 2
    - Name: "Categories"
      URL: "/categories/"
      weight: 3
    - Name: "Tags"
      URL: "/tags/"
      weight: 4
    - Name: "About"
      URL: "/about/"
      weight: 5

params:
  Blogger: "Hao Ren"
  Subtitle: "Software Engineer in Machine Learning"
  GithubID: "invkrh"
  TwitterID: "invkrh"
  LinkedInID: "renhao"
  GmailID: "invkrh"
  # AnalyticsID: "UA-74632317-1"
  DisqusShortname: "invkrh"
  Summary: false # takes true or false
  Comments: true
  # if both are set to true, summary is shown
